### ISSUE TITLE
Hey! just a small request.

### ISSUE THREAD

**Issue by Jerome226** [Superfrogman98/TerraNexCorp#1]
Basically I am doing a TFC+ pack and I would like to make the Dragon API/TFC rain conflict fix into a seperate thing.
Not planning to make any money with it and will stay on github only.

**Comment by Superfrogman98** [comment]
A release of the rain fix has been published at https://github.com/Superfrogman98/TerraNexCorp/releases/tag/Standalone

**Comment by Jerome226** [comment]
Thanks you for this! Saves me the hassle for making it :)
